version: '3.7'
services:
  backend:
    image: currency-conversion-backend:latest
    ports:
      - '3000:3000'
  web:
    image: currency-conversion-frontend:latest
    ports:
      - '80:80'
    depends_on:
      - backend
  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_PASSWORD: mysecretpassword
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
